name=Pinoo Modules
version=1.0.0
author=Pinoo Robotics & Mobility Software
maintainer=Semih Aydın <semih@mobilitysoftware.net>
sentence=A comprehensive Arduino library for Pinoo education boards.
paragraph=Pinoo SDK simplifies electronics education for students and educators by providing clear, English-based programming abstractions for Pinoo ONE and other Pinoo platforms.
category=Device Control
url=https://github.com/mobilitysoftware/PinooSDK
architectures=*
depends=Adafruit NeoPixel, IRremote, LiquidCrystal I2C
